"""Create finance and category tables

Revision ID: 9dc208237850
Revises: 
Create Date: 2023-08-08 21:09:50.649329

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9dc208237850'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('category', sa.Text(), nullable=True),
                    sa.Column('created_on', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('finances',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('concept', sa.Text(), nullable=False),
                    sa.Column('amount', sa.DECIMAL(precision=12, scale=2),
                              nullable=False),
                    sa.Column('total', sa.DECIMAL(precision=12, scale=2),
                              nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('automatic', sa.Boolean(), nullable=True),
                    sa.Column('origin', sa.Text(), nullable=False),
                    sa.Column('created_on', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_on', sa.DateTime(timezone=True),
                              nullable=True),
                    sa.ForeignKeyConstraint(['category_id'],
                                            ['categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finances')
    op.drop_table('categories')
    # ### end Alembic commands ###
